version: '3.7'
services:
  aws_lambda:
    build:
      context: ./docker_src/aws_lambda
    image: aws_lambda
  blancer:
    build:
      context: ./docker_src/balancer
    ports:
      - 9001:9001
    image: blancer
