openapi: 3.0.0
info:
  title: sample server
  description: sample server
  version: 1.0.0
servers:
- url: http://localhost:9001
paths:
  /api/v1/hello:
    get:
      summary: return hello world
      responses:
        default:
          description: success
          content:
            application/json:
              schema:
                type: string
      operationId: hello_world
      x-openapi-router-controller: balancer.api
